GET https://monitor4home.herokuapp.com/api/meter_readings/readings
Accept: application/json

###

POST https://monitor4home.herokuapp.com/api/meter_readings/readings
Content-Type: application/json

{
  "meterNumber": "8927364",
  "reading": 100.78
}