GET https://monitor4home.herokuapp.com/api/meter_readings/readings
Accept: application/json

###

POST https://monitor4home.herokuapp.com/api/meter_readings/readings
Content-Type: application/json

{
  "meterNumber": "8765454344773434",
  "date": "03-09-2021",
  "reading": 67.0,
  "location": "Block D Level 7"
}